line-length = 79
exclude = [".venv/", "*/migrations/"]

[lint]
extend-select = ["I", "E", "W", "F", "C", "D202", "ERA"]
preview = true

[lint.extend-per-file-ignores]
"settings.py" = ["E501"]

[lint.isort]
combine-as-imports = true
order-by-type = false
known-first-party = ['apps']

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "single"
