# Generated by Django 5.1.7 on 2025-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_tag_slug_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_path',
            field=models.FilePathField(path='D:\\Users\\NovaHFly\\Documents\\Portals\\development\\projects_personal\\diary_project\\diary_project\\data'),
        ),
    ]
